### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by kapujiang** [lily-lee/qcloud-cos-go-sdk#1]
`➜  go go get github.com/lily-lee/qcloud-cos-go-sdk/cos
# github.com/lily-lee/qcloud-cos-go-sdk/cos
src/github.com/lily-lee/qcloud-cos-go-sdk/cos/bucket.go:125: invalid operation md5.Sum(data)[:] (slice of unaddressable value)`

**Comment by lily-lee** [comment]
Yes. And it has been fixed. Try again😊
